apiVersion: v1
kind: Service
metadata:
  name: nodetrial-deployment
spec:
  selector:
    app: nodejsservices
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 31110
