name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches:
    - '*'
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: trialservices
      IMAGE_NAME_ENV: trialservices_env
      PROJECT_ID: voicetotext-379213
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/auth@v2


      with:
        service_account: 'speechtotext@voicetotext-379213.iam.gserviceaccount.com'
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: Build Docker Image
      run: |-
       docker build -t $IMAGE_NAME:latest .
       docker build -t $IMAGE_NAME_ENV:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      env:
        # GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        GIT_TAG: v0.1.0
    - name: Push Docker Image to Artifact Registry
      run: |-      
       docker image list
       docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
       gcloud artifacts docker images delete gcr.io/$PROJECT_ID/$IMAGE_NAME_ENV:latest
       docker tag $IMAGE_NAME_ENV:latest gcr.io/$PROJECT_ID/$IMAGE_NAME_ENV:latest
       docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
       docker push gcr.io/$PROJECT_ID/$IMAGE_NAME_ENV:latest      
        
     
