name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches:
    - '*'
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: trialservices
      PROJECT_ID: voicetotext-379213
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    

    - uses: google-github-actions/auth@v2
      with:
        service_account: 'speechtotext@voicetotext-379213.iam.gserviceaccount.com'
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet


      env:
        # GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        GIT_TAG: v0.1.0
        SRC_IMG_1: $IMAGE_NAME:latest
        DEST_IMG_1: gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        DEST_IMG_2: gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG

    - name: Push Docker Image to Artifact Registry
      run: |-
        echo $SRC_IMG_1
        echo $DEST_IMG_1
        echo $DEST_IMG_2        
        docker image list
        
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG

        docker image list


#   # - name: Push Docker Image to Container Registry (GCR)
#   env:
#     # GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
#     GIT_TAG: v0.1.0
#   run: |-
#     docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
#     docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
#     docker push us-central1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
#     docker push us-central1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
